import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Counter from '@/components/Counter'
import Whyus from '@/components/Whyus'
import HowMuchEarn from '@/components/HowMuchEarn'
import Bitcoins from '@/components/Bitcoins'
import Detail from '@/components/Detail'
import StartMining from '@/components/StartMining'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto webisite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* components here */}
      <Header />
      <Counter />
      <Whyus />
      <HowMuchEarn />
      <Bitcoins />
      <Detail />
      <StartMining />
      <Footer />

    </>
  )
}
